try:
    a = 5
    b = 0
    c = a / b
except Exception as e:
    print("다음과 같은 오류가 발생하였습니다 : {}".format(e))